import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{
  //   type: 'autogenerated', dirName: '.'
  // }],
  // But you can create a sidebar manually
  presSidebar: [
    'pres/intro',
    'pres/features',
    {
      type: 'category',
      label: 'Concepts',
      items: ['pres/concepts/gateway', 'pres/concepts/organization', 'pres/concepts/access-control', 'pres/concepts/locales', 'pres/concepts/users-infos'],
    },
    'pres/design'
  ],
  tutoSidebar: [
    'tuto/contents',
    'tuto/install',
    'tuto/setup',
    'tuto/role',
    {
      type: 'category',
      label: 'Route',
      collapsible: false,
      collapsed: false,
      items: [
        'tuto/route/route',
        'tuto/route/route-frontend',
        'tuto/route/route-security',
        'tuto/route/route-authentication',
        'tuto/route/route-predicate',
        'tuto/route/route-filter',
        'tuto/route/route-save-activate'
      ]
    },
    {
      type: 'category',
      label: 'Initialization',
      collapsible: false,
      collapsed: false,
      items: [
        'tuto/init/role-group',
        'tuto/init/group-user',
        'tuto/init/token'
      ]
    },
    {
      type: 'category',
      label: 'Test the route',
      collapsible: false,
      collapsed: false,
      items: [
        'tuto/test/test-ui',
        'tuto/test/test-headers',
        'tuto/test/test-api'
      ]
    },
  ],
  docuSidebar: [
    'doc/start',
    {
      type: 'category',
      label: 'Configuration',
      collapsible: true,
      collapsed: false,
      items: [
        // 'doc/conf/files', 
        'doc/conf/https', 
        'doc/conf/clusterization'
      ],
    },
    {
      type: 'category',
      label: 'User Profile',
      collapsible: true,
      collapsed: false,
      items: [
        'doc/user-profil/me', 
        'doc/user-profil/user-infos',
        'doc/user-profil/organizations',
        'doc/user-profil/tokens',
        'doc/user-profil/connections',
      ],
    },
    {
      type: 'category',
      label: 'Organization',
      collapsible: true,
      collapsed: false,
      items: [
        'doc/organization/organization', 
        'doc/organization/configuration', 
        'doc/organization/members',
        'doc/organization/groups',
      ],
    },
    'doc/sessions',
    'doc/password-policy',
    'doc/target-host',
    {
      type: 'category',
      label: 'Gateway',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Route',
          collapsible: true,
          collapsed: false,
          items: [
            'doc/gateway/route/alternative-target', 
          ],
        },
      ],
    }
  ],
};

export default sidebars;
