import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{
  //   type: 'autogenerated', dirName: '.'
  // }],
  // But you can create a sidebar manually
  presSidebar: [
    'pres/intro',
    'pres/features',
    {
      type: 'category',
      label: 'Concepts',
      items: ['pres/concepts/gateway', 'pres/concepts/organization', 'pres/concepts/access-control', 'pres/concepts/locales', 'pres/concepts/users-infos'],
    },
    'pres/design'
  ],
  tutoSidebar: [
    'tuto/contents',
    'tuto/install',
    'tuto/setup',
    'tuto/role',
    {
      type: 'category',
      label: 'Route',
      collapsible: false,
      collapsed: false,
      items: [
        'tuto/route/route',
        'tuto/route/route-frontend',
        'tuto/route/route-security',
        'tuto/route/route-authentication',
        'tuto/route/route-predicate',
        'tuto/route/route-filter',
        'tuto/route/route-save-activate'
      ]
    },
    {
      type: 'category',
      label: 'Initialization',
      collapsible: false,
      collapsed: false,
      items: [
        'tuto/init/role-group',
        'tuto/init/group-user',
        'tuto/init/token'
      ]
    },
    {
      type: 'category',
      label: 'Test the route',
      collapsible: false,
      collapsed: false,
      items: [
        'tuto/test/test-ui',
        'tuto/test/test-headers',
        'tuto/test/test-api'
      ]
    },
  ],
  docuSidebar: [
    'doc/start',
    {
      type: 'category',
      label: 'Configuration',
      collapsible: false,
      collapsed: false,
      items: [
        // 'doc/conf/files', 
        'doc/conf/https', 
        'doc/conf/clusterization'
      ],
    },
    {
      type: 'category',
      label: 'User Profile',
      collapsible: true,
      collapsed: true,
      items: [
        'doc/user-profil/me', 
        'doc/user-profil/user-infos',
        'doc/user-profil/organizations',
      ],
    },
    'doc/password-policy',
    'doc/target-host',
    {
      type: 'category',
      label: 'Gateway',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Route',
          collapsible: true,
          collapsed: true,
          items: [
            'doc/gateway/route/alternative-target', 
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'User Interface',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Access Control',
          collapsible: true,
          collapsed: true,
          items: [
            'doc/ui/access-control/user-mng', 
            'doc/ui/access-control/roles-mng', 
            'doc/ui/access-control/view-connection-histo',
            'doc/ui/access-control/policies-n-session',
            'doc/ui/access-control/ldap-cfg',
            'doc/ui/access-control/smtp-cfg',
          ],
        },
        {
          type: 'category',
          label: 'Application',
          collapsible: true,
          collapsed: true,
          items: [
            'doc/ui/application/ui-options', 
            'doc/ui/application/notification-push', 
            'doc/ui/application/jwt-options', 
            'doc/ui/application/dev-options', 
            'doc/ui/application/locales', 
          ],
        },
        {
          type: 'category',
          label: 'Gateway',
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'Routes',
              collapsible: true,
              collapsed: true,
              items: [
                'doc/ui/gateway/routes', 
                'doc/ui/gateway/predicates', 
                'doc/ui/gateway/filters', 
              ],
            },
            {
              type: 'category',
              label: 'Endpoints',
              collapsible: true,
              collapsed: true,
              items: [
                'doc/ui/gateway/endpoints-security', 
              ],
            },
            'doc/ui/gateway/vault', 
          ],
        },
      ]
    },
  ],
};

export default sidebars;
